include: package:flutter_lints/flutter.yaml
analyzer:
  errors:
    invalid_annotation_target: ignore
  exclude:
    - fixtures/**
    - lib/**/*.g.dart
linter:
  rules:
    - prefer_relative_imports
    - prefer_single_quotes