include: package:flutter_lints/flutter.yaml

analyzer:
  errors:
    invalid_annotation_target: ignore
  exclude:
    - fixtures/**
    - '**/*.g.dart'
    - '**/*.freezed.dart'
    - '**/*.config.dart'
    - '**/*.gen.dart'
    - '**/feature**/*_test.dart'

linter:
  rules:
    - prefer_relative_imports
    - prefer_single_quotes