targets:
  $default:
    builders:
      envied_generator:
        generate_for:
          - lib/constants/env.dart
      riverpod_generator:
        generate_for:
          - lib/drivers/*.dart
          - lib/app**/*.dart
          - lib/features**/*.dart
          - lib/theme/*.dart
          - lib/l10n/*.dart