name: clinic
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.3.4 <4.0.0'

dependencies:
  connectivity_plus: ^6.0.3
  flutter:
    sdk: flutter
  go_router: ^14.1.1
  path_provider: ^2.1.3
  phosphor_flutter: ^2.1.0
  shared_preferences: ^2.2.3
  hooks_riverpod: ^2.5.1
  flutter_hooks:
  riverpod_annotation: ^2.3.5
  json_annotation: ^4.9.0
  freezed_annotation: ^2.4.1
  dio: ^5.4.3+1
  riverpod: ^2.5.1
  flutter_secure_storage: ^9.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  build_runner:
  custom_lint:
  riverpod_generator: ^2.4.0
  riverpod_lint: ^2.3.10
  json_serializable: ^6.8.0
  freezed: ^2.5.2

flutter:
  uses-material-design: true
  fonts:
    - family: CalSans
      fonts:
        - asset: fonts/CalSans-SemiBold.otf
          weight: 600
    - family: Geist
      fonts:
        - asset: fonts/Geist-Regular.ttf
        - asset: fonts/Geist-Medium.ttf
          weight: 500
        - asset: fonts/Geist-SemiBold.ttf
          weight: 600
        - asset: fonts/Geist-Bold.ttf
          weight: 700