name: clinic
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.3.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: any

  envied: ^0.5.4+1
  flutter_hooks: ^0.20.5
  fl_query: ^1.1.0
  fl_query_hooks: ^1.1.0
  fl_query_connectivity_plus_adapter: ^0.1.0+1
  freezed_annotation: ^2.4.1
  json_annotation: ^4.9.0

  phosphor_flutter: ^2.1.0
  websafe_svg: ^3.0.1+1
  intl_phone_number_input: ^0.7.4
  flutter_otp_text_field: ^1.1.3+2

  connectivity_plus: ^4.0.2
  dio: ^5.4.3+1
  path_provider: ^2.1.3
  flutter_secure_storage: ^9.1.1
  shared_preferences: ^2.2.3
  get_it: ^7.7.0
  injectable: ^2.4.2
  go_router: ^14.1.4
  provider: ^6.1.2
  google_nav_bar: ^5.0.6
  native_toast: ^0.0.2
  cached_network_image: ^3.3.1
  sqflite: ^2.3.3+1
  flutter_cache_manager: ^3.3.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  build_runner:
  json_serializable: ^6.8.0
  freezed: ^2.5.2
  envied_generator: ^0.5.4+1
  injectable_generator: ^2.6.1

flutter:
  generate: true
  uses-material-design: true
  fonts:
    - family: CalSans
      fonts:
        - asset: fonts/CalSans-SemiBold.otf
          weight: 600
    - family: Geist
      fonts:
        - asset: fonts/Geist-Regular.ttf
        - asset: fonts/Geist-Medium.ttf
          weight: 500
        - asset: fonts/Geist-SemiBold.ttf
          weight: 600
        - asset: fonts/Geist-Bold.ttf
          weight: 700
  assets:
    - assets/icons/
    - assets/images/

flutter_intl:
  enabled: true
  output_dir: lib/l10n/generated