name: clinic
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.3.4 <4.0.0'

dependencies:
  connectivity_plus: ^6.0.3
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: any

  riverpod: ^2.5.1
  riverpod_annotation: ^2.3.5
  hooks_riverpod: ^2.5.1
  flutter_hooks:
  go_router: ^14.1.1
  envied: ^0.5.4+1
  json_annotation: ^4.9.0
  freezed_annotation: ^2.4.1

  phosphor_flutter: ^2.1.0
  websafe_svg: ^3.0.1+1
  intl_phone_number_input: ^0.7.4

  dio: ^5.4.3+1
  path_provider: ^2.1.3
  flutter_secure_storage: ^9.1.1
  shared_preferences: ^2.2.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  build_runner:
  custom_lint:
  riverpod_generator: ^2.4.0
  riverpod_lint: ^2.3.10
  json_serializable: ^6.8.0
  freezed: ^2.5.2
  envied_generator: ^0.5.4+1
  retrofit_generator: ^8.1.0

flutter:
  generate: true
  uses-material-design: true
  fonts:
    - family: CalSans
      fonts:
        - asset: fonts/CalSans-SemiBold.otf
          weight: 600
    - family: Geist
      fonts:
        - asset: fonts/Geist-Regular.ttf
        - asset: fonts/Geist-Medium.ttf
          weight: 500
        - asset: fonts/Geist-SemiBold.ttf
          weight: 600
        - asset: fonts/Geist-Bold.ttf
          weight: 700
  assets:
    - assets/icons/
    - assets/images/

flutter_intl:
  enabled: true
  output_dir: lib/l10n/generated