name: clinic
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.3.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  connectivity_plus: ^4.0.2
  device_info_plus: ^10.1.0
  easy_localization: ^3.0.7
  freezed_annotation: ^2.4.1
  json_annotation: ^4.9.0
  path_provider: ^2.1.3
  permission_handler: ^11.3.1

  dio: ^5.4.3+1
  faker_dart: ^0.2.2
  fl_query:
  fl_query_hooks:
  fl_query_connectivity_plus_adapter:
  flutter_hooks: ^0.20.5
  flutter_secure_storage: ^9.2.2
  flutter_cache_manager: ^3.3.2
  isar: ^3.1.0+1
  isar_flutter_libs: ^3.1.0+1
  sqflite: ^2.3.3+1
  state_beacon: ^1.0.0

  auto_route: ^8.2.0
  auto_size_text: ^3.0.0
  cached_network_image: ^3.3.1
  flutter_native_splash: ^2.4.0
  form_validator: ^2.1.1
  image_cropper: ^7.0.4
  image_picker: ^1.1.2
  intl_phone_number_input: ^0.7.4
  phosphor_flutter: ^2.1.0
  pinput: ^4.0.0
  skeletonizer: ^1.3.0
  toastification: ^2.0.0
  websafe_svg: ^3.0.1+1
  wolt_modal_sheet: ^0.7.1
  
dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0
  custom_lint:
  state_beacon_lint:

  auto_route_generator:
  build_runner: ^2.4.9
  isar_generator:
  json_serializable: ^6.8.0
  freezed: ^2.5.2

  flutter_launcher_icons: "^0.13.1"

flutter:
  uses-material-design: true
  fonts:
    - family: CalSans
      fonts:
        - asset: fonts/CalSans-SemiBold.otf
          weight: 600
    - family: Geist
      fonts:
        - asset: fonts/Geist-Regular.ttf
        - asset: fonts/Geist-Medium.ttf
          weight: 500
        - asset: fonts/Geist-SemiBold.ttf
          weight: 600
        - asset: fonts/Geist-Bold.ttf
          weight: 700
  assets:
    - assets/icons/
    - assets/images/
    - assets/launcher/
    - i18n/

flutter_launcher_icons:
  android: "ic_launcher"
  ios: true
  image_path: "assets/launcher/icon.png"
  adaptive_icon_foreground: "assets/launcher/foreground.png"
  adaptive_icon_background: "assets/launcher/background.png"
  min_sdk_android: 21 # android min sdk min:16, default 21
  remove_alpha_ios: true

flutter_native_splash:
  color: "#f7fbf2"
  color_dark: "#101510"
  image: "assets/launcher/foreground.png"