// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBC5ibtD1apvQ5X8COjZXYscUvFqF07eAQ',
    appId: '1:752059788700:android:5035a39adf6776c4e16c59',
    messagingSenderId: '752059788700',
    projectId: 'clinic-ai-66a1a',
    storageBucket: 'clinic-ai-66a1a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB2OIVbHSHsd7DWKkB0m2cLYUgD_yLylBE',
    appId: '1:752059788700:ios:9159979e11eacf9ce16c59',
    messagingSenderId: '752059788700',
    projectId: 'clinic-ai-66a1a',
    storageBucket: 'clinic-ai-66a1a.firebasestorage.app',
    androidClientId: '752059788700-ibipifql3mpp6gupie9t6u1n1vqqhuh2.apps.googleusercontent.com',
    iosClientId: '752059788700-boblbl1fpedgr0ombsc33h52q6d6le2t.apps.googleusercontent.com',
    iosBundleId: 'clinic-ai.com.clinicAi',
  );
}
