// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDUUmywHoHhyUQzcL053Obb6aPnu49l9b0',
    appId: '1:997166988553:android:3aeff8d521b43d13dc27d8',
    messagingSenderId: '997166988553',
    projectId: 'quiet-container-457603-q3',
    storageBucket: 'quiet-container-457603-q3.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDbygEdJVzsEsGS3YpIWuvGqounD7Op0Fc',
    appId: '1:997166988553:ios:b3ebc2fffe88cdb8dc27d8',
    messagingSenderId: '997166988553',
    projectId: 'quiet-container-457603-q3',
    storageBucket: 'quiet-container-457603-q3.firebasestorage.app',
    iosClientId: '997166988553-g5jcpnuf5a010u9gghnd7ftbereq5u51.apps.googleusercontent.com',
    iosBundleId: 'clinic-ai.com.clinicAi',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDM3eJpB53413VS4SEQyBRZUt7QV0tRSBE',
    appId: '1:997166988553:web:1f4fd6a8825bccecdc27d8',
    messagingSenderId: '997166988553',
    projectId: 'quiet-container-457603-q3',
    authDomain: 'quiet-container-457603-q3.firebaseapp.com',
    storageBucket: 'quiet-container-457603-q3.firebasestorage.app',
    measurementId: 'G-5B6SBKCYWS',
  );

}