part of 'app_pages.dart';
// DO NOT EDIT. This is code generated via package:get_cli/get_cli.dart

abstract class Routes {
  Routes._();
  static const HOME = _Paths.HOME;
  static const VERIVICATION = _Paths.VERIVICATION;
  static const VERIVICATION_SUCCESS = _Paths.VERIVICATION_SUCCESS;
  static const SPLASH_SCREEN = _Paths.SPLASH_SCREEN;
  static const ONBOARDING_PAGE = _Paths.ONBOARDING_PAGE;
  static const LOGIN = _Paths.LOGIN;
  // static const REGISTER = _Paths.REGISTER;
  static const PERSONAL_DATA = _Paths.PERSONAL_DATA;
  static const ACCOUNT_SETTINGS = _Paths.ACCOUNT_SETTINGS;
  static const APPOINTMENT = _Paths.APPOINTMENT;
  static const SCHEDULE_APPOINTMENT = _Paths.SCHEDULE_APPOINTMENT;
  static const BARCODE_APPOINTMENT = _Paths.BARCODE_APPOINTMENT;
  static const SYMPTOM_APPOINTMENT = _Paths.SYMPTOM_APPOINTMENT;
  static const CAPTURE_APPOINTMENT = _Paths.CAPTURE_APPOINTMENT;
  static const ADMIN_PANEL = _Paths.ADMIN_PANEL;
  static const CLINIC = _Paths.CLINIC;
  static const LIST_USER = _Paths.LIST_USER;
  static const POLY = _Paths.POLY;
  static const DOCTOR = _Paths.DOCTOR;
  static const SCHEDULE_DATE = _Paths.SCHEDULE_DATE;
  static const SCHEDULE_TIME = _Paths.SCHEDULE_TIME;
  static const UPLOAD = _Paths.UPLOAD;
  static const PROFILE = _Paths.PROFILE;
  static const LIST_PATIENTS = _Paths.LIST_PATIENTS;
  static const QR_SCANNER_SCREEN = _Paths.QR_SCANNER_SCREEN;
  static const HOME_DOCTOR = _Paths.HOME_DOCTOR;
  static const NOTIFICATION_USER = _Paths.NOTIFICATION_USER;
  static const SUMMARY_APPOINTMENT = _Paths.SUMMARY_APPOINTMENT;
  static const HELP_CENTER = _Paths.HELP_CENTER;
  static const DETAIL_DIAGNOSE = _Paths.DETAIL_DIAGNOSE;
  static const REDEEM_MEDICINE = _Paths.REDEEM_MEDICINE;
  static const ABOUT_APP = _Paths.ABOUT_APP;
  static const DRUG_ADMIN = _Paths.DRUG_ADMIN;
  static const MEDICAL_HISTORY = _Paths.MEDICAL_HISTORY;
  static const THEME = _Paths.THEME;
}

abstract class _Paths {
  _Paths._();
  static const HOME = '/home';
  static const ADMIN_PANEL = '/admin-panel';
  static const VERIVICATION = '/verivication';
  static const VERIVICATION_SUCCESS = '/verivication-success';
  static const SPLASH_SCREEN = '/splash-screen';
  static const ONBOARDING_PAGE = '/onboarding-page';
  static const LOGIN = '/login';
  // static const REGISTER = '/register';
  static const PERSONAL_DATA = '/personal-data';
  static const ACCOUNT_SETTINGS = '/account-settings';
  static const APPOINTMENT = '/appointment';
  static const SCHEDULE_APPOINTMENT = '/schedule-appointment';
  static const BARCODE_APPOINTMENT = '/barcode-appointment';
  static const SYMPTOM_APPOINTMENT = '/symptom-appointment';
  static const CAPTURE_APPOINTMENT = '/capture-appointment';
  static const CLINIC = '/clinic';
  static const LIST_USER = '/list-user';
  static const POLY = '/poly';
  static const DOCTOR = '/doctor';
  static const SCHEDULE_DATE = '/schedule-date';
  static const SCHEDULE_TIME = '/schedule-time';
  static const UPLOAD = '/upload';
  static const PROFILE = '/profile';
  static const LIST_PATIENTS = '/list-patients';
  static const QR_SCANNER_SCREEN = '/qr-scanner-screen';
  static const HOME_DOCTOR = '/home-doctor';
  static const NOTIFICATION_USER = '/notification-user';
  static const SUMMARY_APPOINTMENT = '/summary-appointment';
  static const HELP_CENTER = '/help-center';
  static const DETAIL_DIAGNOSE = '/detail-diagnose';
  static const REDEEM_MEDICINE = '/redeem-medicine';
  static const ABOUT_APP = '/about-app';
  static const DRUG_ADMIN = '/drug-admin';
  static const MEDICAL_HISTORY = '/medical-history';
  static const THEME = '/theme';
}
