name: Flutter build preview release app pipeline

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # Checkout github repo
      - uses: actions/checkout@v4

      # Create env file later used by build_runner envied
      - name: Create env file
        run: |
          touch .env
          echo API_BASE_URL=${{ secrets.API_BASE_URL }} >> .env

      # Setup flutter, install dependencies, and generated codes
      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable
          architecture: x64
      - run: |
          git config --global --add safe.directory /opt/hostedtoolcache/flutter/${{ steps.flutter-action.outputs.CHANNEL }}-${{ steps.flutter-action.outputs.VERSION }}-${{ steps.flutter-action.outputs.ARCHITECTURE }}
          flutter --version
      - name: Install Dependencies
        run: flutter pub get
      - name: Build Generated Codes
        run: dart run build_runner build -d